name: project cicd flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker-demo .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker-demo

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Server and Pull Docker Image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 156.67.81.207
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/tp1/mohamed
            docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-image-new
            docker stop container-mohammed || true
            docker rm container-mohammed || true
            docker run -d --name container-mmohamed -p 3213:3213 -v /home/tp1/mohamed/app ${{ secrets.DOCKER_USERNAME }}/springboot-image-new:Latest
