name: project cicd flow

on:
  push:
    branches:
      - main
    paths:
      - med-el-ferjani/**
      - .github/workflows/*.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: mohammedferjani/springboot-image-new:latest
          registry: registry-url.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Server and Pull Docker Image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 156.67.81.207
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/tp1/mohamedferjani
            docker pull registry-url.io/mohamedferjani/springboot-image-new:latest
            docker stop container-abdel || true
            docker rm container-abdel || true
            docker run -d --name container-abdel -p 2024:2312 -v /home/tp1/mohamedferjani:/app registry-url.io/mohamedferjani/springboot-image-new:latest
